### ISSUE TITLE
주소록 만들기

### ISSUE THREAD

**Issue by winterfall98** [inven-dev-study/hello-javascript#7]
2021-06-22(화)까지!

밋치&로크
뮤이&베르

```
입력
수정
삭제
정렬
즐겨찾기(상단고정)
검색(필터링)

이름을 누르면  
  -> 상세정보(전화번호, 이메일)
  -> 버튼: 수정, 삭제, 즐겨찾기 추가

```
데이터는  >  객체로 ...  이름 전화번호 이메일
                      입력, 수정시에 유효값 체크

참고:
https://brunch.co.kr/@jfrences/84

https://ifuwanna.tistory.com/138

**Comment by winterfall98** [comment]
마크업 (이름을 누르면 펼쳐짐 등등 동작)
&: 입력 수정 정렬   -> 밋치

삭제 즐찾 검색   -> 로크

**Comment by door0** [comment]
입력 수정 (즐겨찾기) 삭제  UI 상세 페이지 -> 베르

마크업 (이름을 누르면 펼쳐짐 등등 동작) 
& 검색 정렬  UI 목록 페이지 (index.html)  -> 뮤이

**Comment by inven-dev-study** [comment]
## 코드리뷰

### [베르&뮤이]
- hasOwnProperty : 프로퍼티인지 아닌지 확인
- subItme = person
- innerHTML 과 createElement() 차이
- innerHTML : DOM이 parsing 함, 대용량 데이터 처리할 때 비효율적
- createElement과 push, join('') 이용하면 됨
- 사람을 class로 잡는게 좋음
- "keyup" = "input"
- keyup : 한글 입력이 됨, space, ctrl 시 계속 나옴
- input : 실제로 써질 때. 이벤트 트리거 생김
- includes 보다는 indexOf 사용
- 검색시 키워드.trim(); 해주기 (앞뒤 공백 없애줌)
- switch문을 js에서 지양하기 (비효율적)

### [밋치&로크]
- lazyload : 디스플레이 안보일 때 안 불러 오는 것, 퍼포먼스 확실함
- 인벤 사이트 중 lazyload 사용한 사이트 : 하스스톤
- 인벤 사이트 중 lazyload 사용하지 않은 사이트 : 와우
- before() = insertBefore(detailbox, targetList, firstChild);
- after() = appendChild();
- keyup은 document 에서 하면 안됨.
